# Generated by Django 3.1.1 on 2020-09-23 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('手机号', models.CharField(default=1, max_length=11)),
                ('昵称', models.CharField(default='', max_length=32)),
                ('性别', models.NullBooleanField(default=0)),
                ('出生日期', models.DateField(default='2000-06-06')),
                ('个人形象', models.ImageField(default='', upload_to='')),
                ('居住地', models.CharField(default='北京', max_length=64)),
            ],
        ),
    ]
